name: Build documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: self-hosted
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache-dependency-path: "kit/package-lock.json"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set environment variables
        run: |
          cd optimum
          version=`echo "$(grep '^__version__ =' furiosa/version.py | cut -d '=' -f 2- | xargs)"`

          if [[ $version == *.dev0 ]]
          then
            echo "VERSION=main" >> $GITHUB_ENV
          else
            echo "VERSION=v$version" >> $GITHUB_ENV
          fi

          cd ..

      - name: Setup environment
        run: |
          python -m venv venv_docs
          source venv_docs/bin/activate
          python -m pip install --upgrade pip
          python -m ensurepip --upgrade
          python -m pip install --upgrade setuptools
          python -m pip install git+https://github.com/huggingface/doc-builder
          python -m pip install .[quality]

      - name: Make documentation
        run: |
          source venv-doc/bin/activate
          sudo apt install software-properties-common
          sudo add-apt-repository --remove https://packages.microsoft.com/ubuntu/22.04/prod
          sudo apt update
          sudo apt install -y ca-certificates apt-transport-https gnupg
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 5F03AFA423A751913F249259814F888B20B09A7E
          sudo tee -a /etc/apt/auth.conf.d/furiosa.conf > /dev/null <<EOT
            machine archive.furiosa.ai
            login ${{ secrets.FURIOSA_ACCESS_KEY }}
            password ${{ secrets.FURIOSA_SECRET_ACCESS_KEY }}
          EOT
          sudo chmod 400 /etc/apt/auth.conf.d/furiosa.conf
          sudo tee -a /etc/apt/sources.list.d/furiosa.list <<EOT
            deb [arch=amd64] https://archive.furiosa.ai/ubuntu jammy restricted
          EOT
          sudo apt update && sudo apt install -y furiosa-libnux

      - name: Make documentation
        shell: bash
        run: |
          source venv-doc/bin/activate
          doc-builder build optimum.furiosa docs/source/ \
            --repo_name optimum-furiosa \
            --build_dir furiosa-doc-build/ \
            --version ${{ env.VERSION }} \
            --version_tag_suffix "" \
            --html \
            --clean \

      - name: Push documentation
        run: |
          source venv-doc/bin/activate
          sudo chmod -R ugo+rwx furiosa-doc-build
          cd furiosa-doc-build
          sudo mv optimum.furiosa optimum-furiosa
          doc-builder push optimum-furiosa --doc_build_repo_id "hf-doc-build/doc-build" --token "${{ secrets.HF_DOC_BUILD_PUSH }}" --commit_msg "Updated with commit $COMMIT_SHA See: https://github.com/huggingface/optimum-furiosa/commit/$COMMIT_SHA" --n_retries 5
