name: Check code quality

on:
  push:
    branches: [ main ]
    paths:
      - "optimum/**.py"
      - "tests/**.py"
      - "examples/**.py"

  pull_request:
    branches: [ main ]
    paths:
      - "optimum/**.py"
      - "tests/**.py"
      - "examples/**.py"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e  # v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install black ruff
    - name: Check style with black
      run: |
        source venv/bin/activate
        black --check .
    - name: Check style with ruff
      run: |
        source venv/bin/activate
        ruff .