name: Delete doc comment trigger

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@17ccdf17e0f5e5f88b1ce9f20b3b73fb19017169  # main
    with:
      pr_number: ${{ github.event.number }}
